# Generated by Django 3.1.3 on 2020-11-25 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rezerwacje', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='room',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='room',
            name='slug',
            field=models.SlugField(max_length=40, unique=True),
            preserve_default=False,
        ),
    ]
