# Generated by Django 3.1.3 on 2020-11-26 15:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rezerwacje', '0002_auto_20201125_0116'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='coordinators',
            field=models.ManyToManyField(through='rezerwacje.Coordinator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='room',
            name='room_keepers',
            field=models.ManyToManyField(through='rezerwacje.RoomKeeper', to=settings.AUTH_USER_MODEL),
        ),
    ]
