# Generated by Django 3.1.3 on 2020-11-28 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rezerwacje', '0004_room_available'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='slug',
        ),
    ]
